# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/test-release-3',
                'doc_host': 'https://tylere.github.io',
                'git_url': 'https://github.com/tylere/test-release-3',
                'lib_path': 'test_release_3'},
  'syms': {'test_release_3.core': {'test_release_3.core.foo': ('core.html#foo', 'test_release_3/core.py')}}}